### ISSUE TITLE
how to set ip admin login?

### ISSUE THREAD

**Issue by one9three** [UndernetIRC/cservice-web#10]
![67FCC695-4B49-409A-A809-06C582B93649](https://user-images.githubusercontent.com/66469410/86010148-94357180-ba4d-11ea-95d9-4226c7994fde.jpeg)

hi, can you help me how to fix ip address admin login.

**Comment by one9three** [comment]
> ![67FCC695-4B49-409A-A809-06C582B93649](https://user-images.githubusercontent.com/66469410/86010148-94357180-ba4d-11ea-95d9-4226c7994fde.jpeg)
> 
> hi, can you help me how to fix ip address admin login.

**Comment by tenye2003** [comment]
In order to bypass the IPR restriction on webpage login for Admin account, we use the following steps:
su - gnuworld
pico ipr.sql
insert into ip_restrict (id, user_id, added_by, added, type, expiry, value) values (1, 1, 1, now()::abstime::int4, 1, 0, '192.168.1.100');
#Replace 192.168.1.100 with your local IP address.

source : ZioN's forum
